name: Pyright Type Check

on: [push, pull_request]

jobs:
  pyright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Pyright
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Pyright
        run: npm install -g pyright

      - name: Run Pyright
        run: pyright
