name: Python application test with Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install pytest
    - name: Test with pytest
      run: |
        python -m pytest test/